package com.softech.alfasdk.Util;

import com.softech.alfasdk.Models.CityTownVillageModel.CityTownVillage;

import java.util.ArrayList;

public class CityTownVillages {

    public static ArrayList<CityTownVillage> getCityTownVillages(){

        ArrayList<CityTownVillage> mListCities = new ArrayList<>();
        mListCities.add(new CityTownVillage("1", "ABBOTTABAD"));
        mListCities.add(new CityTownVillage("2", "ADEZAI"));
        mListCities.add(new CityTownVillage("3", "AHMED NAGER CHATHA"));
        mListCities.add(new CityTownVillage("4", "AHMEDPUR EAST"));
        mListCities.add(new CityTownVillage("5", "ALI BANDAR"));
        mListCities.add(new CityTownVillage("6", "ALI PUR"));
        mListCities.add(new CityTownVillage("7", "AMIR CHAH"));
        mListCities.add(new CityTownVillage("8", "ARIFWALA"));
        mListCities.add(new CityTownVillage("9", "ASTOR"));
        mListCities.add(new CityTownVillage("10", "ATTOCK"));
        mListCities.add(new CityTownVillage("11", "AYUBIA"));
        mListCities.add(new CityTownVillage("12", "BADEN"));
        mListCities.add(new CityTownVillage("13", "BAGH"));
        mListCities.add(new CityTownVillage("14", "BAHAWALNAGAR"));
        mListCities.add(new CityTownVillage("15", "BAHAWALPUR"));
        mListCities.add(new CityTownVillage("16", "BAJAUR"));
        mListCities.add(new CityTownVillage("17", "BANDA DAUD SHAH"));
        mListCities.add(new CityTownVillage("18", "BANNU"));
        mListCities.add(new CityTownVillage("19", "BARAMULA"));
        mListCities.add(new CityTownVillage("20", "BASTI MALOOK"));
        mListCities.add(new CityTownVillage("21", "BATAGRAM"));
        mListCities.add(new CityTownVillage("22", "BAZDAR"));
        mListCities.add(new CityTownVillage("23", "BELA"));
        mListCities.add(new CityTownVillage("24", "BELLPAT"));
        mListCities.add(new CityTownVillage("25", "BHAG"));
        mListCities.add(new CityTownVillage("26", "BHAGALCHUR"));
        mListCities.add(new CityTownVillage("27", "BHAIPHERU"));
        mListCities.add(new CityTownVillage("28", "BHAKKAR"));
        mListCities.add(new CityTownVillage("29", "BHALWAL"));
        mListCities.add(new CityTownVillage("30", "BHIMBER"));
        mListCities.add(new CityTownVillage("31", "BIROTE"));
        mListCities.add(new CityTownVillage("32", "BUNER"));
        mListCities.add(new CityTownVillage("33", "BUREWALA"));
        mListCities.add(new CityTownVillage("34", "BURJ"));
        mListCities.add(new CityTownVillage("35", "CHACHRO"));
        mListCities.add(new CityTownVillage("36", "CHAGAI"));
        mListCities.add(new CityTownVillage("37", "CHAH SANDAN"));
        mListCities.add(new CityTownVillage("38", "CHAILIANWALA"));
        mListCities.add(new CityTownVillage("39", "CHAKDARA"));
        mListCities.add(new CityTownVillage("40", "CHAKKU"));
        mListCities.add(new CityTownVillage("41", "CHAKWAL"));
        mListCities.add(new CityTownVillage("42", "CHAMAN"));
        mListCities.add(new CityTownVillage("43", "CHARSADDA"));
        mListCities.add(new CityTownVillage("44", "CHHATR"));
        mListCities.add(new CityTownVillage("45", "CHICHAWATNI"));
        mListCities.add(new CityTownVillage("46", "CHINIOT"));
        mListCities.add(new CityTownVillage("47", "CHITRAL"));
        mListCities.add(new CityTownVillage("48", "CHOWK AZAM"));
        mListCities.add(new CityTownVillage("49", "CHOWK SARWAR SHAHEED"));
        mListCities.add(new CityTownVillage("50", "CHUNIA"));
        mListCities.add(new CityTownVillage("51", "DADU"));
        mListCities.add(new CityTownVillage("52", "DADYAL"));
        mListCities.add(new CityTownVillage("53", "DAHARKI"));
        mListCities.add(new CityTownVillage("54", "DALBANDIN"));
        mListCities.add(new CityTownVillage("55", "DARGAI"));
        mListCities.add(new CityTownVillage("56", "DARYA KHAN"));
        mListCities.add(new CityTownVillage("57", "DARYA KHAN"));
        mListCities.add(new CityTownVillage("58", "DASKA"));
        mListCities.add(new CityTownVillage("59", "DERA BUGTI"));
        mListCities.add(new CityTownVillage("60", "DERA GHAZI KHAN"));
        mListCities.add(new CityTownVillage("61", "DERA ISMAIL KHAN"));
        mListCities.add(new CityTownVillage("62", "DERAWAR FORT"));
        mListCities.add(new CityTownVillage("63", "DHANA SAR"));
        mListCities.add(new CityTownVillage("64", "DHAULAR"));
        mListCities.add(new CityTownVillage("65", "DHUNGI"));
        mListCities.add(new CityTownVillage("66", "DIGRI"));
        mListCities.add(new CityTownVillage("67", "DINA CITY"));
        mListCities.add(new CityTownVillage("68", "DINGA"));
        mListCities.add(new CityTownVillage("69", "DIPALPUR"));
        mListCities.add(new CityTownVillage("70", "DIPLO"));
        mListCities.add(new CityTownVillage("71", "DIR"));
        mListCities.add(new CityTownVillage("72", "DIWANA"));
        mListCities.add(new CityTownVillage("73", "DOKRI"));
        mListCities.add(new CityTownVillage("74", "DRASAN"));
        mListCities.add(new CityTownVillage("75", "DROSH"));
        mListCities.add(new CityTownVillage("76", "DUKI"));
        mListCities.add(new CityTownVillage("77", "DUSHI"));
        mListCities.add(new CityTownVillage("78", "DUZAB"));
        mListCities.add(new CityTownVillage("79", "FAISALABAD"));
        mListCities.add(new CityTownVillage("80", "FATEH JANG"));
        mListCities.add(new CityTownVillage("81", "GADAR"));
        mListCities.add(new CityTownVillage("82", "GADRA"));
        mListCities.add(new CityTownVillage("83", "GAJAR"));
        mListCities.add(new CityTownVillage("84", "GANDAVA"));
        mListCities.add(new CityTownVillage("85", "GARHI KHAIRO"));
        mListCities.add(new CityTownVillage("86", "GARRUCK"));
        mListCities.add(new CityTownVillage("87", "GHAKHAR MANDI"));
        mListCities.add(new CityTownVillage("88", "GHANIAN"));
        mListCities.add(new CityTownVillage("89", "GHAUSPUR"));
        mListCities.add(new CityTownVillage("90", "GHAZLUNA"));
        mListCities.add(new CityTownVillage("91", "GHOTKI"));
        mListCities.add(new CityTownVillage("92", "GILGIT"));
        mListCities.add(new CityTownVillage("93", "GIRDAN"));
        mListCities.add(new CityTownVillage("94", "GOJRA"));
        mListCities.add(new CityTownVillage("95", "GOTH MACHI"));
        mListCities.add(new CityTownVillage("96", "GUJAR KHAN"));
        mListCities.add(new CityTownVillage("97", "GUJRANWALA"));
        mListCities.add(new CityTownVillage("98", "GUJRAT"));
        mListCities.add(new CityTownVillage("99", "GULISTAN"));
        mListCities.add(new CityTownVillage("100", "GWADAR"));
        mListCities.add(new CityTownVillage("101", "GWASH"));
        mListCities.add(new CityTownVillage("102", "HAB CHAUKI"));
        mListCities.add(new CityTownVillage("103", "HAFIZABAD"));
        mListCities.add(new CityTownVillage("104", "HALA (SINDH) HALA"));
        mListCities.add(new CityTownVillage("105", "HAMEEDABAD"));
        mListCities.add(new CityTownVillage("106", "HANGU"));
        mListCities.add(new CityTownVillage("107", "HANGU"));
        mListCities.add(new CityTownVillage("108", "HARIPUR"));
        mListCities.add(new CityTownVillage("109", "HARNAI"));
        mListCities.add(new CityTownVillage("110", "HAROONABAD"));
        mListCities.add(new CityTownVillage("111", "HASAN ABDAL"));
        mListCities.add(new CityTownVillage("112", "HASILPUR"));
        mListCities.add(new CityTownVillage("113", "HATTIAN BALA"));
        mListCities.add(new CityTownVillage("114", "HAVELI LAKHA"));
        mListCities.add(new CityTownVillage("115", "HINGLAJ"));
        mListCities.add(new CityTownVillage("116", "HOSHAB"));
        mListCities.add(new CityTownVillage("117", "HUB"));
        mListCities.add(new CityTownVillage("118", "HUNZA"));
        mListCities.add(new CityTownVillage("119", "HYDERABAD"));
        mListCities.add(new CityTownVillage("120", "ISLAMABAD"));
        mListCities.add(new CityTownVillage("121", "ISLAMKOT"));
        mListCities.add(new CityTownVillage("122", "ISPIKAN"));
        mListCities.add(new CityTownVillage("123", "JACOBABAD"));
        mListCities.add(new CityTownVillage("124", "JAFFERABAD"));
        mListCities.add(new CityTownVillage("125", "JAHANIA"));
        mListCities.add(new CityTownVillage("126", "JALLA ARAAIN"));
        mListCities.add(new CityTownVillage("127", "JAMESABAD"));
        mListCities.add(new CityTownVillage("128", "JAMPUR"));
        mListCities.add(new CityTownVillage("129", "JAMSHORO"));
        mListCities.add(new CityTownVillage("130", "JANGHAR"));
        mListCities.add(new CityTownVillage("131", "JARANWALA"));
        mListCities.add(new CityTownVillage("132", "JATI"));
        mListCities.add(new CityTownVillage("133", "JAUHARABAD"));
        mListCities.add(new CityTownVillage("134", "JHAL"));
        mListCities.add(new CityTownVillage("135", "JHAL JHAO"));
        mListCities.add(new CityTownVillage("136", "JHAL MAGSI"));
        mListCities.add(new CityTownVillage("137", "JHANG"));
        mListCities.add(new CityTownVillage("138", "JHATPAT"));
        mListCities.add(new CityTownVillage("139", "JHELUM"));
        mListCities.add(new CityTownVillage("140", "JHUDO"));
        mListCities.add(new CityTownVillage("141", "JIWANI"));
        mListCities.add(new CityTownVillage("142", "JUNGSHAHI"));
        mListCities.add(new CityTownVillage("143", "KALABAGH"));
        mListCities.add(new CityTownVillage("144", "KALAM"));
        mListCities.add(new CityTownVillage("145", "KALANDI"));
        mListCities.add(new CityTownVillage("146", "KALAT"));
        mListCities.add(new CityTownVillage("147", "KAMALIA"));
        mListCities.add(new CityTownVillage("148", "KAMARAROD"));
        mListCities.add(new CityTownVillage("149", "KAMBER"));
        mListCities.add(new CityTownVillage("150", "KAMOKEY"));
        mListCities.add(new CityTownVillage("151", "KANAK"));
        mListCities.add(new CityTownVillage("152", "KANDHKOT"));
        mListCities.add(new CityTownVillage("153", "KANDI"));
        mListCities.add(new CityTownVillage("154", "KANDIARO"));
        mListCities.add(new CityTownVillage("155", "KANPUR"));
        mListCities.add(new CityTownVillage("156", "KAPIP"));
        mListCities.add(new CityTownVillage("157", "KAPPAR"));
        mListCities.add(new CityTownVillage("158", "KARACHI"));
        mListCities.add(new CityTownVillage("159", "KARAK"));
        mListCities.add(new CityTownVillage("160", "KARODI"));
        mListCities.add(new CityTownVillage("161", "KAROR LAL ESAN"));
        mListCities.add(new CityTownVillage("162", "KASHMOR"));
        mListCities.add(new CityTownVillage("163", "KASUR"));
        mListCities.add(new CityTownVillage("164", "KATURI"));
        mListCities.add(new CityTownVillage("165", "KETI BANDAR"));
        mListCities.add(new CityTownVillage("166", "KHAIRPUR"));
        mListCities.add(new CityTownVillage("167", "KHAIRPUR MIRIS"));
        mListCities.add(new CityTownVillage("168", "KHANASPUR"));
        mListCities.add(new CityTownVillage("169", "KHANEWAL"));
        mListCities.add(new CityTownVillage("170", "KHANPUR"));
        mListCities.add(new CityTownVillage("171", "KHARAN"));
        mListCities.add(new CityTownVillage("172", "KHARIAN"));
        mListCities.add(new CityTownVillage("173", "KHOKHROPUR"));
        mListCities.add(new CityTownVillage("174", "KHORA"));
        mListCities.add(new CityTownVillage("175", "KHUIRATTA"));
        mListCities.add(new CityTownVillage("176", "KHUSHAB"));
        mListCities.add(new CityTownVillage("177", "KHUZDAR"));
        mListCities.add(new CityTownVillage("178", "KHYBER"));
        mListCities.add(new CityTownVillage("179", "KIKKI"));
        mListCities.add(new CityTownVillage("180", "KLUPRO"));
        mListCities.add(new CityTownVillage("181", "KOHAN"));
        mListCities.add(new CityTownVillage("182", "KOHAT"));
        mListCities.add(new CityTownVillage("183", "KOHISTAN"));
        mListCities.add(new CityTownVillage("184", "KOHLU"));
        mListCities.add(new CityTownVillage("185", "KORAK"));
        mListCities.add(new CityTownVillage("186", "KOT ADDU"));
        mListCities.add(new CityTownVillage("187", "KOT SARAE"));
        mListCities.add(new CityTownVillage("188", "KOTLI"));
        mListCities.add(new CityTownVillage("189", "KOTRI"));
        mListCities.add(new CityTownVillage("190", "KURRAM"));
        mListCities.add(new CityTownVillage("191", "LAAR"));
        mListCities.add(new CityTownVillage("192", "LAHORE"));
        mListCities.add(new CityTownVillage("193", "LAHRI"));
        mListCities.add(new CityTownVillage("194", "LAKKI MARWAT"));
        mListCities.add(new CityTownVillage("195", "LALAMUSA"));
        mListCities.add(new CityTownVillage("196", "LARKANA"));
        mListCities.add(new CityTownVillage("197", "LASBELA"));
        mListCities.add(new CityTownVillage("198", "LATAMBER"));
        mListCities.add(new CityTownVillage("199", "LAYYAH"));
        mListCities.add(new CityTownVillage("200", "LIARI"));
        mListCities.add(new CityTownVillage("201", "LODHRAN"));
        mListCities.add(new CityTownVillage("202", "LORALAI"));
        mListCities.add(new CityTownVillage("203", " DIR"));
        mListCities.add(new CityTownVillage("204", "LUND"));
        mListCities.add(new CityTownVillage("205", "MACH"));
        mListCities.add(new CityTownVillage("206", "MADYAN"));
        mListCities.add(new CityTownVillage("207", "MAILSI"));
        mListCities.add(new CityTownVillage("208", "MAKHDOOM AALI"));
        mListCities.add(new CityTownVillage("209", "MALAKAND"));
        mListCities.add(new CityTownVillage("210", "MALAKAND"));
        mListCities.add(new CityTownVillage("211", "MAMOORI"));
        mListCities.add(new CityTownVillage("212", "MAND"));
        mListCities.add(new CityTownVillage("213", "MANDI BAHAUDDIN"));
        mListCities.add(new CityTownVillage("214", "MANDI WARBURTON"));
        mListCities.add(new CityTownVillage("215", "MANGLA"));
        mListCities.add(new CityTownVillage("216", "MANGUCHAR"));
        mListCities.add(new CityTownVillage("217", "MANSEHRA"));
        mListCities.add(new CityTownVillage("218", "MARDAN"));
        mListCities.add(new CityTownVillage("219", "MASHKI CHAH"));
        mListCities.add(new CityTownVillage("220", "MASLTI"));
        mListCities.add(new CityTownVillage("221", "MASTUJ"));
        mListCities.add(new CityTownVillage("222", "MASTUNG"));
        mListCities.add(new CityTownVillage("223", "MATHI"));
        mListCities.add(new CityTownVillage("224", "MATIARI"));
        mListCities.add(new CityTownVillage("225", "MATLI"));
        mListCities.add(new CityTownVillage("226", "MEHAR"));
        mListCities.add(new CityTownVillage("227", "MEKHTAR"));
        mListCities.add(new CityTownVillage("228", "MERUI"));
        mListCities.add(new CityTownVillage("229", "MIAN CHANNU"));
        mListCities.add(new CityTownVillage("230", "MIANEZ"));
        mListCities.add(new CityTownVillage("231", "MIANWALI"));
        mListCities.add(new CityTownVillage("232", "MINAWALA"));
        mListCities.add(new CityTownVillage("233", "MIRAM SHAH"));
        mListCities.add(new CityTownVillage("234", "MIRPUR"));
        mListCities.add(new CityTownVillage("235", "MIRPUR BATORO"));
        mListCities.add(new CityTownVillage("236", "MIRPUR KHAS"));
        mListCities.add(new CityTownVillage("237", "MIRPUR MATHELO"));
        mListCities.add(new CityTownVillage("238", "MIRPUR SAKRO"));
        mListCities.add(new CityTownVillage("239", "MITHANI"));
        mListCities.add(new CityTownVillage("240", "MITHI"));
        mListCities.add(new CityTownVillage("241", "MOHMAND"));
        mListCities.add(new CityTownVillage("242", "MOIN JO DARO"));
        mListCities.add(new CityTownVillage("243", "MONGORA"));
        mListCities.add(new CityTownVillage("244", "MORO"));
        mListCities.add(new CityTownVillage("245", "MULTAN"));
        mListCities.add(new CityTownVillage("246", "MURGHA KIBZAI"));
        mListCities.add(new CityTownVillage("247", "MURIDKE"));
        mListCities.add(new CityTownVillage("248", "MURREE"));
        mListCities.add(new CityTownVillage("249", "MUSA KHEL BAZAR"));
        mListCities.add(new CityTownVillage("250", "MUZAFFARABAD"));
        mListCities.add(new CityTownVillage("251", "MUZAFFARGARH"));
        mListCities.add(new CityTownVillage("252", "NAGAR"));
        mListCities.add(new CityTownVillage("253", "NAGAR PARKAR"));
        mListCities.add(new CityTownVillage("254", "NAGHA KALAT"));
        mListCities.add(new CityTownVillage("255", "NAL"));
        mListCities.add(new CityTownVillage("256", "NANKANA SAHIB"));
        mListCities.add(new CityTownVillage("257", "NAOKOT"));
        mListCities.add(new CityTownVillage("258", "NAROWAL"));
        mListCities.add(new CityTownVillage("259", "NASEERABAD"));
        mListCities.add(new CityTownVillage("260", "NAUDERO"));
        mListCities.add(new CityTownVillage("261", "NAUROZ KALAT"));
        mListCities.add(new CityTownVillage("262", "NAUSHARA"));
        mListCities.add(new CityTownVillage("263", "NAUSHERO FEROZE"));
        mListCities.add(new CityTownVillage("264", "NAWABSHAH"));
        mListCities.add(new CityTownVillage("265", "NAZIMABAD"));
        mListCities.add(new CityTownVillage("266", "NEELUM"));
        mListCities.add(new CityTownVillage("267", "NORTH WAZIRISTAN"));
        mListCities.add(new CityTownVillage("268", "NOWSHERA"));
        mListCities.add(new CityTownVillage("269", "NUR GAMMA"));
        mListCities.add(new CityTownVillage("270", "NUSHKI"));
        mListCities.add(new CityTownVillage("271", "NUTTAL"));
        mListCities.add(new CityTownVillage("272", "OKARA"));
        mListCities.add(new CityTownVillage("273", "ORMARA"));
        mListCities.add(new CityTownVillage("274", "PAHARPUR"));
        mListCities.add(new CityTownVillage("275", "PAK PATTAN"));
        mListCities.add(new CityTownVillage("276", "PALANTUK"));
        mListCities.add(new CityTownVillage("277", "PANJGUR"));
        mListCities.add(new CityTownVillage("278", "PANJGUR"));
        mListCities.add(new CityTownVillage("279", "PANOAKIL"));
        mListCities.add(new CityTownVillage("280", "PARACHINAR"));
        mListCities.add(new CityTownVillage("281", "PASNI"));
        mListCities.add(new CityTownVillage("282", "PATTOKI"));
        mListCities.add(new CityTownVillage("283", "PEACOCK"));
        mListCities.add(new CityTownVillage("284", "PENDOO"));
        mListCities.add(new CityTownVillage("285", "PESHAWAR"));
        mListCities.add(new CityTownVillage("286", "PIHARAK"));
        mListCities.add(new CityTownVillage("287", "PIRMAHAL"));
        mListCities.add(new CityTownVillage("288", "PISHIN"));
        mListCities.add(new CityTownVillage("289", "PLANDRI"));
        mListCities.add(new CityTownVillage("290", "POKRAN"));
        mListCities.add(new CityTownVillage("291", "PUNCH"));
        mListCities.add(new CityTownVillage("292", "QAMBAR"));
        mListCities.add(new CityTownVillage("293", "QAMRUDDIN KAREZ"));
        mListCities.add(new CityTownVillage("294", "QAZI AHMAD"));
        mListCities.add(new CityTownVillage("295", "QILA ABDULLAH"));
        mListCities.add(new CityTownVillage("296", "QILA DIDAR SINGH"));
        mListCities.add(new CityTownVillage("297", "QILA LADGASHT"));
        mListCities.add(new CityTownVillage("298", "QILA SAFED"));
        mListCities.add(new CityTownVillage("299", "QILA SAIFULLAH"));
        mListCities.add(new CityTownVillage("300", "QUETTA"));
        mListCities.add(new CityTownVillage("301", "RABWAH"));
        mListCities.add(new CityTownVillage("302", "RAHIM YAR KHAN"));
        mListCities.add(new CityTownVillage("303", "RAIWIND"));
        mListCities.add(new CityTownVillage("304", "RAJAN PUR"));
        mListCities.add(new CityTownVillage("305", "RAKHNI"));
        mListCities.add(new CityTownVillage("306", "RANIPUR"));
        mListCities.add(new CityTownVillage("307", "RATODERO"));
        mListCities.add(new CityTownVillage("308", "RAWALAKOT"));
        mListCities.add(new CityTownVillage("309", "RAWALPINDI"));
        mListCities.add(new CityTownVillage("310", "RENALA KHURD"));
        mListCities.add(new CityTownVillage("311", "ROBAT THANA"));
        mListCities.add(new CityTownVillage("312", "RODKHAN"));
        mListCities.add(new CityTownVillage("313", "ROHRI"));
        mListCities.add(new CityTownVillage("314", "ROHRI"));
        mListCities.add(new CityTownVillage("315", "SADIQABAD"));
        mListCities.add(new CityTownVillage("316", "SAFDARABAD-DABANSING"));
        mListCities.add(new CityTownVillage("317", "SAHIWAL"));
        mListCities.add(new CityTownVillage("318", "SAIDU SHARIF"));
        mListCities.add(new CityTownVillage("319", "SAIDU SHARIF"));
        mListCities.add(new CityTownVillage("320", "SAINDAK"));
        mListCities.add(new CityTownVillage("321", "SAKESAR"));
        mListCities.add(new CityTownVillage("322", "SAKRAND"));
        mListCities.add(new CityTownVillage("323", "SAMBERIAL"));
        mListCities.add(new CityTownVillage("324", "SANGHAR"));
        mListCities.add(new CityTownVillage("325", "SANGLA HILL"));
        mListCities.add(new CityTownVillage("326", "SANJAWI"));
        mListCities.add(new CityTownVillage("327", "SARAI ALAMGIR"));
        mListCities.add(new CityTownVillage("328", "SARGODHA"));
        mListCities.add(new CityTownVillage("329", "SARUNA"));
        mListCities.add(new CityTownVillage("330", "SHABAZ KALAT"));
        mListCities.add(new CityTownVillage("331", "SHADADKHOT"));
        mListCities.add(new CityTownVillage("332", "SHAFQAT SHAHED CHOWK"));
        mListCities.add(new CityTownVillage("333", "SHAHBANDAR"));
        mListCities.add(new CityTownVillage("334", "SHAHDADPUR"));
        mListCities.add(new CityTownVillage("335", "SHAHPUR"));
        mListCities.add(new CityTownVillage("336", "SHAHPUR CHAKAR"));
        mListCities.add(new CityTownVillage("337", "SHAKARGARH"));
        mListCities.add(new CityTownVillage("338", "SHANDUR"));
        mListCities.add(new CityTownVillage("339", "SHANGLA"));
        mListCities.add(new CityTownVillage("340", "SHANGRILA"));
        mListCities.add(new CityTownVillage("341", "SHARAM JOGIZAI"));
        mListCities.add(new CityTownVillage("342", "SHARAQPUR"));
        mListCities.add(new CityTownVillage("343", "SHEIKHUPURA"));
        mListCities.add(new CityTownVillage("344", "SHIKARPUR"));
        mListCities.add(new CityTownVillage("345", "SHINGAR"));
        mListCities.add(new CityTownVillage("346", "SHORAP"));
        mListCities.add(new CityTownVillage("347", "SIALKOT"));
        mListCities.add(new CityTownVillage("348", "SIBI"));
        mListCities.add(new CityTownVillage("349", "SKARDU"));
        mListCities.add(new CityTownVillage("350", "SOHAWA"));
        mListCities.add(new CityTownVillage("351", "SONMIANI"));
        mListCities.add(new CityTownVillage("352", "SOOIANWALA"));
        mListCities.add(new CityTownVillage("353", "SOUTH WAZIRISTAN"));
        mListCities.add(new CityTownVillage("354", "SPEZAND"));
        mListCities.add(new CityTownVillage("355", "SPINTANGI"));
        mListCities.add(new CityTownVillage("356", "SUDHNOTI"));
        mListCities.add(new CityTownVillage("357", "SUI"));
        mListCities.add(new CityTownVillage("358", "SUJAWAL"));
        mListCities.add(new CityTownVillage("359", "SUKKUR"));
        mListCities.add(new CityTownVillage("360", "SUNDAR"));
        mListCities.add(new CityTownVillage("361", "SUNTSAR"));
        mListCities.add(new CityTownVillage("362", "SURAB"));
        mListCities.add(new CityTownVillage("363", "SWABI"));
        mListCities.add(new CityTownVillage("364", "SWAT"));
        mListCities.add(new CityTownVillage("365", "TAKHTBAI"));
        mListCities.add(new CityTownVillage("366", "TALAGANG"));
        mListCities.add(new CityTownVillage("367", "TANDLIANWALA"));
        mListCities.add(new CityTownVillage("368", "TANDO ADAM"));
        mListCities.add(new CityTownVillage("369", "TANDO ALAH YAR"));
        mListCities.add(new CityTownVillage("370", "TANDO BAGO"));
        mListCities.add(new CityTownVillage("371", "TANDO MUHAMMAD KHAN"));
        mListCities.add(new CityTownVillage("372", "TANGI"));
        mListCities.add(new CityTownVillage("373", "TANK"));
        mListCities.add(new CityTownVillage("374", "TAR AHAMD RIND"));
        mListCities.add(new CityTownVillage("375", "TARBELA"));
        mListCities.add(new CityTownVillage("376", "TAXILA"));
        mListCities.add(new CityTownVillage("377", "THALL"));
        mListCities.add(new CityTownVillage("378", "THALO"));
        mListCities.add(new CityTownVillage("379", "THARPARKAR"));
        mListCities.add(new CityTownVillage("380", "THATTA"));
        mListCities.add(new CityTownVillage("381", "TIMARGARA"));
        mListCities.add(new CityTownVillage("382", "TOBA TEK SINGH"));
        mListCities.add(new CityTownVillage("383", "TORDHER"));
        mListCities.add(new CityTownVillage("384", "TUJAL"));
        mListCities.add(new CityTownVillage("385", "TUMP"));
        mListCities.add(new CityTownVillage("386", "TURBAT"));
        mListCities.add(new CityTownVillage("387", "UBARO"));
        mListCities.add(new CityTownVillage("388", "UMARAO"));
        mListCities.add(new CityTownVillage("389", "UMARKOT"));
        mListCities.add(new CityTownVillage("390", "UPPER DIR"));
        mListCities.add(new CityTownVillage("391", "UTHAL"));
        mListCities.add(new CityTownVillage("392", "VEHARI"));
        mListCities.add(new CityTownVillage("393", "VEIRWARO"));
        mListCities.add(new CityTownVillage("394", "VITAKRI"));
        mListCities.add(new CityTownVillage("395", "WADH"));
        mListCities.add(new CityTownVillage("396", "WAH CANTT"));
        mListCities.add(new CityTownVillage("397", "WANA"));
        mListCities.add(new CityTownVillage("398", "WARAH"));
        mListCities.add(new CityTownVillage("399", "WASHAP"));
        mListCities.add(new CityTownVillage("400", "WASJUK"));
        mListCities.add(new CityTownVillage("401", "WAZIRABAD"));
        mListCities.add(new CityTownVillage("402", "YAKMACH"));
        mListCities.add(new CityTownVillage("403", "ZHOB"));
        mListCities.add(new CityTownVillage("404", "ZIARAT"));

        return mListCities;
    }

}
